export const FRENCH_EXPERIENCIES = {
  experiencies: {
    title: "Expériences",
    mediakeys:
      'En **CDI** chez [Mediakeys](https://www.mediakeys.com/) en tant que développeur web Front-End.\n\nJe travaille sur divers projets, les deux principaux étant une plateforme permettant aux entreprises / media trader de gérer leurs campagnes publicitaires, de partout dans le monde, sur divers media tel que Facebook, Instagram, divers sites internets, etc, et une application permettant de créer des banières publicitaires pour ces mêmes media.\nPour mener à bien la création de nouvelles applis et l\'évolution de ceux déjà existant, je fais:\n\n- Création de maquette dites "wire-frame"\n- Création de nouveaux composants et container\n- Rédaction de tests unitaires\n- Proposition de nouvelles fonctionalités\n- Rédaction de documentation\n- Cérémonies Agile\n\n**Librairies utilisées:** React, Redux, Redux Sagas, Moment, Moment JS, Material-UI, Jest, etc ...',
    hcube:
      "En **CDI** chez [HCube Conseil](https://www.hcube-conseil.fr/) pendant près d'**un an et demi**, j'ai travaillé pour la **Française des Jeux** en qualité de Développeur React/Redux.\n\nLe projet consistait à refondre les parcours web d'inscription, de connexion et de la gestion du compte. Pour ce faire, tout au long du projet, j'ai eu pour mission :\n\n- Rétro-ingénierie sur les applications existantes\n- POC d'un formulaire d'inscription\n- Intégration de maquettes réalisées sous Zeplin\n- Initiation à React et Redux auprès de nouveaux arrivants\n- Cérémonies Agile (review, planing, retro, etc)\n- Création de composants et containers \n- Rédaction de tests unitaires\n- Rédaction de documentation\n\n**Librairies utilisées :** React, Redux, Redux Sagas, Redux toolkit, Dayjs, Jest, Material UI, Styled-components, etc...",
    buyco:
      "**Première experience professionnelle** de 6 mois en **CDI** en tant que **développeur web**, j'ai eu pour tâche pendant plusieurs mois de réaliser le **POC** d'une toute nouvelle application en **React**.\n\nLes 4 autres mois, j'ai travaillé avec un autre développeur et le tech-lead sur l'application principale sur des missions tels que:\n\n- Rédaction de tests unitaires\n- Réalisation de maquettes\n- Création de composants\n- Création de sagas\n- Création de reducer\n- Débug de fonctionalités existantes\n- Participation aux cérémonies Agile\n\n\n**Librairies utilisées :** React, Redux, Redux Sagas, Moment, Jest, Enzyme, Semantic-UI, etc...",
    opquast:
      "[Opquast](https://www.opquast.com/) est une certification professionnelle s'adressant à tout les intervenants d'un projet web. On y voit des points essentiels concernant le SEO, l'accessibilité, la sémantique HTML, le responsive et bien d'autres points très interessants. Au bout de cette formation en autonomie, on peut passer un certificat valable 5 ans attestant du niveau de notre connaissance du web.\n\nJ'ai obtenu un score de **885 / 1000** et ai ainsi décroché mon [certificat](https://directory.opquast.com/fr/certificat/PFE9IM/).\n\n> Ce score signifie : Excellente connaissance des bonnes pratiques qualité du Web et du vocabulaire associé.\nCompétences réelles et appréciables pour participer à des projets Web.\n",
    oclock:
      "[O'Clock](https://oclock.io) est une formation en téléprésentiel où j'ai pu approfondir mes connaissances et ma passion du web.\n\nLa formation se compose d'un socle de 3 mois où l'on découvre **HTML 5**, **CSS 3**, **PhP** et **Javascript**, tout en se familiarisant avec les outils de dev classiques tels que **Git**, **Node**, **NPM**, **Composer**, **Webpack**, etc, etc ...\nA l'issue de ces 3 mois, un mois de spécialisation sur une librarie parmis celles qui nous sont proposées (**React** dans mon cas ❤️), suivi d'un autre mois consacré à la création d'un projet autour de React / Redux.\n\nUne fois la formation terminée, j'ai choisi de me présenter à un examen me donnant accès à un **Bac + 2** (titre de développeur logiciel de rang III)",
    adequat:
      "De Mars à Octobre 2015, j'ai travaillé en tant qu'**interimaire** au sein de la société [Adequat](https://www.lejobadequat.com/). Première experience professionelle, j'ai pu réaliser diverses missions telles que :\n\n- Enquêteur\n- Aide livreur\n- Préparateur de commande\n- Prospecteur\n- Opérateur de saisie\n- Inventoriste\n- Conditionneur",
    ceri: "Après avoir validé une 1re année de Licence informatique au [CERI](http://ceri.univ-avignon.fr/) (Centre d'Enseignement et de Recherche en Informatique) à Avignon, j'ai quitté la fac début décembre 2016 afin de trouver un cursus moins théorique et plus axé sur le développement web.\n",
    bac: "Obtention de mon **Baccalauréat Scientifique, option ISN** (Informatique et Sciences du Numérique) au lycée [Victor Hugo](http://www.lyceevictorhugo.fr/) de Carpentras, au cours duquel, au fil de l'année, je me suis découvert, une passion pour la programmation.",
    birth:
      "Je suis né le 24 Décembre 1996 Marignane.\n\n(Non ce n'est pas nul, c'est même super de fêter Noël et son anniversaire le même soir ! 🙄)",
  },
};
